import os
import json
from datetime import datetime, timedelta

def build_batches():
    print("🚀 Starting Batch Generation...")
    
    # Target Classes
    classes = ["Class 11", "Class 12"]
    
    # Streams and their respective subjects
    streams = {
        "Commerce": ["Economics", "Business Studies (BST)", "Accounts"],
        "Science": ["Physics", "Chemistry", "Mathematics", "Biology"]
    }

    batches = []
    
    # Helper function to format time as '3:00 PM'
    def format_time(dt_obj):
        return dt_obj.strftime("%I:%M %p")

    # Generate schedules
    for target_class in classes:
        for stream, subjects in streams.items():
            
            # Reset start time to 3:00 PM for each stream/class combo
            current_time = datetime.strptime("15:00", "%H:%M")
            
            # Reverse subject order for Class 12 to simulate non-clashing timetables
            schedule_subjects = subjects if target_class == "Class 11" else list(reversed(subjects))
            
            for subject in schedule_subjects:
                # Add 40 minutes for the end time
                end_time = current_time + timedelta(minutes=40)
                
                batch_record = {
                    "batch_name": f"{target_class} {stream} - {subject}",
                    "target_class": target_class,
                    "stream": stream,
                    "subject": subject,
                    "start_time": format_time(current_time),
                    "end_time": format_time(end_time),
                    "duration_minutes": 40,
                    "status": "active"
                }
                
                batches.append(batch_record)
                
                # The end time of this class becomes the start time of the next
                current_time = end_time

    # Construct the final JSON payload
    output_data = {"batches": batches}
    
    # Define file paths (Saving in the current directory, which should be database_template)
    dir_path = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(dir_path, 'batch_template.json')
    js_path = os.path.join(dir_path, 'batch_template.js')

    # 1. Save as JSON
    with open(json_path, 'w', encoding='utf-8') as json_file:
        json.dump(output_data, json_file, indent=2)
    print(f"✅ Created JSON template: {json_path}")

    # 2. Save as JS (for Google Apps Script inclusion)
    js_content = f"""/**
 * @file batch_template.js
 * Contains the batch preset data for DazzlingDB.
 * GENERATED BY build_batches.py
 */

const BATCH_TEMPLATE = {json.dumps(output_data, indent=2)};
"""
    with open(js_path, 'w', encoding='utf-8') as js_file:
        js_file.write(js_content)
    print(f"✅ Created JS template: {js_path}")
    
    print(f"🎉 Successfully generated {len(batches)} batches.")

if __name__ == "__main__":
    build_batches()
