/**
 * @file TestMockHelper.js
 * Centralized Testing Mock Data Factory for DazzlingDB.
 * 
 * Provides baseline randomized mock payload builders matching exact schema columns.
 */

const TestMockHelper = {
  /**
   * Generates a randomized salt string.
   * @private
   * @returns {string} Random 7-character uppercase salt.
   */
  _getSalt: function() {
    return Math.random().toString(36).substring(2, 9).toUpperCase();
  },

  /**
   * Generates a randomized 10-digit mobile phone number starting with 9.
   * @private
   * @returns {string} Phone number string.
   */
  _getPhone: function() {
    return "9" + Math.floor(100000000 + Math.random() * 900000000);
  },

  /**
   * Prepares a randomized CourseType insertion payload.
   * 
   * > [!IMPORTANT]
   * > Do NOT pass `segment_id` in this payload. Let the SheetDB AutoField engine generate it.
   * 
   * @param {Object} [overrides={}] - Column overrides.
   * @returns {Object} Validated CourseType payload.
   */
  createCourseTypePayload: function(overrides = {}) {
    const salt = this._getSalt();
    return {
      segment_name: overrides.segment_name || "Segment " + salt,
      entity_label: overrides.entity_label || "Label " + salt,
      description: overrides.description || "Description " + salt,
      status: overrides.status || "active",
      ...overrides
    };
  },

  /**
   * Prepares a randomized Course insertion payload.
   * 
   * > [!IMPORTANT]
   * > You must supply a valid `segment_id` (CourseType primary key) to link this Course. 
   * > Do NOT supply `course_id` (Course primary key) as it is generated by the database.
   * 
   * @param {string} segmentId - The primary key of the parent CourseType segment (segment_id).
   * @param {Object} [overrides={}] - Column overrides.
   * @returns {Object} Validated Course payload.
   * @throws {Error} If segmentId is not provided.
   */
  createCoursePayload: function(segmentId, overrides = {}) {
    if (!segmentId) throw new Error("segmentId is required to create a Course payload.");
    const salt = this._getSalt();
    return {
      segment_id: segmentId,
      entity_type: overrides.entity_type || "course",
      name: overrides.name || "Course " + salt,
      short_code: overrides.short_code || "C-" + salt,
      language_medium: overrides.language_medium || "English", // Choices: [English, Hindi, Urdu]
      description: overrides.description || "Course description " + salt,
      duration_value: overrides.duration_value || 12,
      duration_unit: overrides.duration_unit || "months", // Choices: [months, days, weeks]
      base_fee: overrides.base_fee || 5000,
      default_installment_count: overrides.default_installment_count || 1,
      status: overrides.status || "active",
      ...overrides
    };
  },

  /**
   * Prepares a randomized Batch insertion payload.
   * 
   * > [!IMPORTANT]
   * > You must supply active foreign keys: `course_id`, `teacher_id`, and `branch_id`.
   * > Do NOT supply `batch_id` as it is generated by the database.
   * 
   * @param {string} courseId - The primary key of the parent Course (course_id).
   * @param {string} teacherId - The primary key of the assigned Teacher (teacher_id).
   * @param {string} branchId - The primary key of the target Branch (branch_id).
   * @param {Object} [overrides={}] - Column overrides.
   * @returns {Object} Validated Batch payload.
   */
  createBatchPayload: function(courseId, teacherId, branchId, overrides = {}) {
    if (!courseId || !teacherId || !branchId) {
      throw new Error("courseId, teacherId, and branchId are required to create a Batch payload.");
    }
    const salt = this._getSalt();
    return {
      course_id: courseId,
      teacher_id: teacherId,
      branch_id: branchId,
      batch_name: overrides.batch_name || "Batch " + salt,
      capacity: overrides.capacity || 30,
      batch_type: overrides.batch_type || "Academy", // Choices: [Academy, Computer, Foundation, Competitive]
      status: overrides.status || "active",
      start_date: overrides.start_date || "2026-06-01",
      end_date: overrides.end_date || "2027-06-01",
      schedule: overrides.schedule || { days_of_week: ["Mon", "Wed"], start_time: "10:00", end_time: "12:00", room: "Room A" },
      ...overrides
    };
  },

  /**
   * Prepares a randomized Package payload suitable for academic_create_package action.
   * 
   * > [!IMPORTANT]
   * > To link nested courses, pass an array of Course primary keys `courseIds` in the payload. 
   * > The helper will map them to the polymorphic `courses` envelope required by AcademicService: 
   * > `[{ entity_type: "course", entity_id: "CRS-XXX" }]`.
   * > Do NOT supply `package_id` as it is auto-generated.
   * 
   * @param {Array<string>} [courseIds=[]] - Array of Course primary keys (course_id) to bundle.
   * @param {Object} [overrides={}] - Column overrides.
   * @returns {Object} Validated Package payload.
   */
  createPackagePayload: function(courseIds = [], overrides = {}) {
    const salt = this._getSalt();
    const coursesPayload = courseIds.map(id => ({
      entity_type: "course",
      entity_id: id
    }));

    return {
      name: overrides.name || "Package " + salt,
      description: overrides.description || "Package description " + salt,
      target_class: overrides.target_class || "Class " + salt,
      board: overrides.board || "CBSE",
      month: overrides.month || 12,
      package_fee: overrides.package_fee || 12000,
      discount_percent: overrides.discount_percent || 0,
      status: overrides.status || "active",
      courses: overrides.courses || coursesPayload,
      perks: overrides.perks || [
        { perk_title: "Mock Perk " + salt, perk_description: "Mock Description", icon: "star" }
      ],
      ...overrides
    };
  },

  /**
   * Prepares a nested payload suitable for RegisterStudentAction (student_register).
   * 
   * > [!IMPORTANT]
   * > You must supply a valid `itemId` (which can be a Course ID or a Package ID).
   * > Use the `enrollmentType` discriminator ("course" | "package") to route the type.
   * > If it is a package enrollment, pass `packageBatches` containing mapped `{ course_id, batch_id }` arrays.
   * 
   * @param {string} itemId - The primary key of the Course or Package being registered (item_id).
   * @param {string} [enrollmentType="course"] - Discriminator type ("course" | "package").
   * @param {Array<Object>} [packageBatches=[]] - Array of course to batch mappings: `[{ course_id, batch_id }]`.
   * @param {Object} [overrides={}] - Profile, address, contact, or fee overrides.
   * @returns {Object} Nested Student Registration payload.
   */
  createStudentRegistrationPayload: function(itemId, enrollmentType = "course", packageBatches = [], overrides = {}) {
    if (!itemId) throw new Error("itemId is required to construct a StudentRegistration payload.");
    const salt = this._getSalt();
    const phone = this._getPhone();
    const fee = overrides.fee || 5000;
    
    return {
      profile: {
        student_name: overrides.student_name || "Student " + salt,
        gender: overrides.gender || "Male",
        dob: overrides.dob || "2006-01-01",
        status: overrides.status || "active",
        mother_name: overrides.mother_name || "Mother " + salt,
        father_name: overrides.father_name || "Father " + salt
      },
      address: {
        line1: overrides.line1 || "Street " + salt,
        city: overrides.city || "Jaipur",
        state: overrides.state || "Rajasthan",
        pin_code: overrides.pin_code || "302017",
        country: overrides.country || "India"
      },
      contact: {
        mobile_number: overrides.mobile_number || phone,
        email: overrides.email || "student_" + salt.toLowerCase() + "@test.com"
      },
      education: overrides.education || [
        {
          highest_qualification: "Class 10",
          institution_name: "Mock Institution " + salt,
          year_of_passing: 2024,
          percentage_or_cgpa: "90%"
        }
      ],
      enrollments: overrides.enrollments || [
        {
          enrollment_type: enrollmentType,
          item_id: itemId,
          fee: fee,
          package_batches: packageBatches
        }
      ],
      feeAccount: overrides.feeAccount || {
        total_fee: fee,
        discount: overrides.discount || 0,
        final_fee: fee - (overrides.discount || 0),
        amount_paid: overrides.amount_paid || 0,
        installments: overrides.installments || [
          {
            installment_number: 1,
            due_amount: fee - (overrides.discount || 0),
            paid_amount: overrides.amount_paid || 0,
            due_date: "2026-06-30"
          }
        ]
      }
    };
  },

  /**
   * Prepares a randomized Student insertion payload containing profile fields.
   * @param {Object} [overrides={}] - Column overrides.
   * @returns {Object} Flat Student profile payload.
   */
  createStudentPayload: function(overrides = {}) {
    const salt = this._getSalt();
    return {
      student_name: overrides.student_name || "Student " + salt,
      email: overrides.email || "student_" + salt.toLowerCase() + "@test.com",
      phone: overrides.phone || this._getPhone(),
      status: overrides.status || "active",
      ...overrides
    };
  },

  /**
   * Prepares a randomized Teacher insertion payload.
   * @param {Object} [overrides={}] - Column overrides.
   * @returns {Object} Validated Teacher payload.
   */
  createTeacherPayload: function(overrides = {}) {
    const salt = this._getSalt();
    return {
      full_name: overrides.full_name || "Teacher " + salt,
      email: overrides.email || "teacher_" + salt.toLowerCase() + "@test.com",
      mobile_number: overrides.mobile_number || this._getPhone(),
      status: overrides.status || "active",
      experience_years: overrides.experience_years || 5,
      teacher_type: overrides.teacher_type || "full_time",
      joining_date: overrides.joining_date || "2026-06-09",
      ...overrides
    };
  },

  /**
   * Prepares a randomized StaffMember insertion payload.
   * @param {Object} [overrides={}] - Column overrides.
   * @returns {Object} Validated StaffMember payload.
   */
  createStaffMemberPayload: function(overrides = {}) {
    const salt = this._getSalt();
    return {
      name: overrides.name || "Staff " + salt,
      role: overrides.role || "security",
      status: overrides.status || "active",
      phone: overrides.phone || this._getPhone(),
      email: overrides.email || "staff_" + salt.toLowerCase() + "@test.com",
      ...overrides
    };
  },

  /**
   * Prepares a randomized ExpenseCategory insertion payload.
   * @param {Object} [overrides={}] - Column overrides.
   * @returns {Object} Validated ExpenseCategory payload.
   */
  createExpenseCategoryPayload: function(overrides = {}) {
    const salt = this._getSalt();
    return {
      name: overrides.name || "Category " + salt,
      type: overrides.type || "both",
      description: overrides.description || "Utility description " + salt,
      ...overrides
    };
  },

  /**
   * Prepares a randomized MoneyTransaction insertion payload satisfying all schema validations.
   * @param {number} amount - Absolute financial magnitude.
   * @param {string} type - Flow direction ("in" | "out").
   * @param {string} categoryId - Foreign key to ExpenseCategory.
   * @param {string} partyType - Polymorphic discriminator type ("student" | "teacher" | "staff" | "external").
   * @param {Object} [overrides={}] - Additional column overrides.
   * @returns {Object} Validated MoneyTransaction payload.
   */
  createMoneyTransactionPayload: function(amount, type, categoryId, partyType, overrides = {}) {
    if (amount === undefined || !type || !categoryId || !partyType) {
      throw new Error("amount, type, categoryId, and partyType are required to create a MoneyTransaction payload.");
    }
    const salt = this._getSalt();
    const payload = {
      amount: amount,
      type: type,
      category_id: categoryId,
      party_type: partyType,
      by: overrides.hasOwnProperty("by") ? overrides.by : (type === "in" ? "Recv By " + salt : "Sent By " + salt),
      from_to: overrides.hasOwnProperty("from_to") ? overrides.from_to : (type === "in" ? "From " + salt : "To " + salt),
      payment_method: overrides.hasOwnProperty("payment_method") ? overrides.payment_method : "cash",
      party_name: overrides.hasOwnProperty("party_name") ? overrides.party_name : "Party " + salt,
      transaction_date: overrides.hasOwnProperty("transaction_date") ? overrides.transaction_date : "2026-06-26",
      reconciliation_status: overrides.hasOwnProperty("reconciliation_status") ? overrides.reconciliation_status : "unreconciled",
      ...overrides
    };

    // Clean up fields set to undefined via overrides to test missing-field validations
    for (const key in payload) {
      if (payload[key] === undefined) {
        delete payload[key];
      }
    }
    return payload;
  }
};

globalThis.TestMockHelper = TestMockHelper;
