/**
 * @file dependency_graph.js
 * Automatically generated by compile-graph. Do not edit manually.
 */

const DEPENDENCY_GRAPH = {
  "Course": [
    {
      "table": "Batch",
      "fk": "course_id",
      "onDelete": "protect"
    },
    {
      "table": "BatchAllocation",
      "fk": "course_id",
      "onDelete": "protect"
    },
    {
      "table": "TeacherSubject",
      "fk": "subject_id",
      "onDelete": "protect"
    }
  ],
  "Teacher": [
    {
      "table": "Batch",
      "fk": "teacher_id",
      "onDelete": "protect"
    },
    {
      "table": "TeacherAttendance",
      "fk": "teacher_id",
      "onDelete": "protect"
    },
    {
      "table": "TeacherDocument",
      "fk": "teacher_id",
      "onDelete": "protect"
    },
    {
      "table": "TeacherPaymentTransaction",
      "fk": "teacher_id",
      "onDelete": "protect"
    },
    {
      "table": "TeacherSalaryConfig",
      "fk": "teacher_id",
      "onDelete": "protect"
    },
    {
      "table": "TeacherSubject",
      "fk": "teacher_id",
      "onDelete": "protect"
    }
  ],
  "Branch": [
    {
      "table": "Batch",
      "fk": "branch_id",
      "onDelete": "protect"
    },
    {
      "table": "Teacher",
      "fk": "branch_id",
      "onDelete": "protect"
    }
  ],
  "Student": [
    {
      "table": "BatchAllocation",
      "fk": "student_id",
      "onDelete": "cascade"
    },
    {
      "table": "Enrollment",
      "fk": "student_id",
      "onDelete": "cascade"
    },
    {
      "table": "StudentAttendance",
      "fk": "student_id",
      "onDelete": "cascade"
    },
    {
      "table": "Address",
      "fk": "student_id",
      "onDelete": "cascade"
    },
    {
      "table": "ContactInfo",
      "fk": "student_id",
      "onDelete": "cascade"
    },
    {
      "table": "Education",
      "fk": "student_id",
      "onDelete": "cascade"
    },
    {
      "table": "TestMarks",
      "fk": "student_id",
      "onDelete": "cascade"
    }
  ],
  "Enrollment": [
    {
      "table": "BatchAllocation",
      "fk": "enrollment_id",
      "onDelete": "protect"
    },
    {
      "table": "StudentFeeAccount",
      "fk": "enrollment_id",
      "onDelete": "cascade"
    }
  ],
  "Batch": [
    {
      "table": "BatchAllocation",
      "fk": "batch_id",
      "onDelete": "protect"
    },
    {
      "table": "StudentAttendance",
      "fk": "batch_id",
      "onDelete": "protect"
    },
    {
      "table": "TeacherAttendance",
      "fk": "batch_id",
      "onDelete": "protect"
    },
    {
      "table": "StudentLead",
      "fk": "batch_id",
      "onDelete": "protect"
    },
    {
      "table": "Test",
      "fk": "batch_id",
      "onDelete": "protect"
    }
  ],
  "CourseType": [
    {
      "table": "Course",
      "fk": "segment_id",
      "onDelete": "protect"
    }
  ],
  "Package": [
    {
      "table": "PackageItem",
      "fk": "package_id",
      "onDelete": "protect"
    },
    {
      "table": "PackagePerk",
      "fk": "package_id",
      "onDelete": "protect"
    }
  ],
  "User": [
    {
      "table": "Session",
      "fk": "user_id",
      "onDelete": "protect"
    }
  ],
  "StudentFeeAccount": [
    {
      "table": "FeeAdjustment",
      "fk": "student_fee_id",
      "onDelete": "protect"
    },
    {
      "table": "Installment",
      "fk": "student_fee_id",
      "onDelete": "protect"
    },
    {
      "table": "Payment",
      "fk": "student_fee_id",
      "onDelete": "protect"
    }
  ],
  "ExpenseCategory": [
    {
      "table": "MoneyTransaction",
      "fk": "category_id",
      "onDelete": "protect"
    }
  ],
  "Installment": [
    {
      "table": "Payment",
      "fk": "installment_id",
      "onDelete": "protect"
    }
  ],
  "FeePlan": [
    {
      "table": "StudentFeeAccount",
      "fk": "fee_plan_id",
      "onDelete": "protect"
    }
  ],
  "TeacherSalaryConfig": [
    {
      "table": "TeacherPaymentTransaction",
      "fk": "salary_config_id",
      "onDelete": "protect"
    }
  ],
  "Address": [
    {
      "table": "ContactInfo",
      "fk": "address_id",
      "onDelete": "cascade"
    }
  ],
  "Test": [
    {
      "table": "TestMarks",
      "fk": "test_id",
      "onDelete": "cascade"
    },
    {
      "table": "TestPaper",
      "fk": "test_id",
      "onDelete": "cascade"
    }
  ]
};
