/**
 * @file GraphBuilder.js
 * Compiles a directed dependency map (adjacency list) and writes it to dependency_graph.js.
 */

const fs = require('fs');
const path = require('path');
const Logger = require('../logger/Logger');

class GraphBuilder {
  /**
   * @param {Object} schemas - Map of { TableName: SchemaObject }
   */
  constructor(schemas) {
    this.schemas = schemas;
  }

  /**
   * Generates the dependency adjacency list.
   * @returns {Object} Adjacency list representation
   */
  build() {
    const graph = {};

    for (const [tableName, schema] of Object.entries(this.schemas)) {
      if (!schema.relations) continue;

      for (const [relName, relSchema] of Object.entries(schema.relations)) {
        if (relSchema.type === 'belongsTo') {
          const parentTable = relSchema.target;
          const fk = relSchema.foreignKey;
          if (!parentTable || !fk) continue;

          const onDelete = relSchema.onDelete || 'protect';

          // Validate target parent table exists
          if (!this.schemas[parentTable]) {
            Logger.warn(`Table '${tableName}' refers to non-existent target table '${parentTable}' in relation '${relName}'.`);
            continue;
          }

          // Validate target parent table has a primary key
          if (!this.schemas[parentTable].primaryKey) {
            Logger.warn(`Table '${tableName}' relation '${relName}' target parent table '${parentTable}' is missing a primary key.`);
            continue;
          }

          // Validate local foreign key column is defined in columns
          if (!schema.columns || !schema.columns[fk]) {
            Logger.warn(`Table '${tableName}' relation '${relName}' foreign key column '${fk}' is not defined in columns.`);
            continue;
          }

          if (!graph[parentTable]) {
            graph[parentTable] = [];
          }

          // Register child table dependency pointing back to parent
          graph[parentTable].push({
            table: tableName,
            fk: fk,
            onDelete: onDelete
          });
        }
      }
    }

    return graph;
  }

  /**
   * Writes the generated dependency graph to DazzlingDB/Config/dependency_graph.js.
   * @param {string} targetPath - Absolute path where dependency_graph.js will be written.
   */
  write(targetPath) {
    try {
      const graph = this.build();
      const fileContent = `/**
 * @file dependency_graph.js
 * Automatically generated by compile-graph. Do not edit manually.
 */

const DEPENDENCY_GRAPH = ${JSON.stringify(graph, null, 2)};
`;

      // Ensure directory exists
      const dir = path.dirname(targetPath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      fs.writeFileSync(targetPath, fileContent, 'utf8');
      Logger.success(`Wrote dependency graph to ${targetPath}`);
    } catch (error) {
      Logger.error(`Failed to write dependency graph to ${targetPath}: ${error.message}`);
      throw error;
    }
  }
}

module.exports = GraphBuilder;
