/**
 * @file GraphBuilder.js
 * Compiles a directed dependency map (adjacency list) and writes it to dependency_graph.js.
 */

const fs = require('fs');
const path = require('path');
const Logger = require('../logger/Logger');

class GraphBuilder {
  /**
   * @param {Object} schemas - Map of { TableName: SchemaObject }
   */
  constructor(schemas) {
    this.schemas = schemas;
  }

  /**
   * Generates the dependency adjacency list.
   * @returns {Object} Adjacency list representation
   */
  build() {
    const graph = {};

    for (const [tableName, schema] of Object.entries(this.schemas)) {
      if (!schema.columns) continue;

      for (const [colName, colSchema] of Object.entries(schema.columns)) {
        if (colSchema.type === 'foreign_key') {
          const parentTable = colSchema.target;
          if (!parentTable) continue;

          const onDelete = colSchema.onDelete || 'protect';

          if (!graph[parentTable]) {
            graph[parentTable] = [];
          }

          // Register child table dependency
          graph[parentTable].push({
            table: tableName,
            fk: colName,
            onDelete: onDelete
          });
        }
      }
    }

    return graph;
  }

  /**
   * Writes the generated dependency graph to DazzlingDB/Config/dependency_graph.js.
   * @param {string} targetPath - Absolute path where dependency_graph.js will be written.
   */
  write(targetPath) {
    const graph = this.build();
    const fileContent = `/**
 * @file dependency_graph.js
 * Automatically generated by compile-graph. Do not edit manually.
 */

const DEPENDENCY_GRAPH = ${JSON.stringify(graph, null, 2)};
`;

    // Ensure directory exists
    const dir = path.dirname(targetPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(targetPath, fileContent, 'utf8');
    Logger.success(`Wrote dependency graph to ${targetPath}`);
  }
}

module.exports = GraphBuilder;
